# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

new_user1 = User.create(username: "Nick", email: "nick@skynet.com", password_digest: 123456)
new_user2 = User.create(username: "Admin", email: "admin@email.com", password_digest: 123456)
new_user3 = User.create(username: "Sidney", email: "sidney@feather.com", password_digest: 123456)

new_job_Nick1 = Job.create(title: "Photographer", company: "Himmel über New York", level: "Junior", salary: 15, description: "Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI.", city: "New York", state: "NY", user_id: 1)
new_job_Nick2 = Job.create(title: "Photo Retoucher", company: "Himmel über New York", level: "Senior", salary: 75, description: "Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI.", city: "New York", state: "NY", user_id: 1)
new_job_Nick3 = Job.create(title: "Model Maker", company: "Himmel über New York", level: "Intern", salary: 0, description: "Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI.", city: "New York", state: "NY", user_id: 1)
new_job_Sidney4 = Job.create(title: "Art Historian", company: "Himmel über New York", level: "Senior", salary: 10, description: "Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI.", city: "New York", state: "NY", user_id: 1)

new_job_Sidney1 = Job.create(title: "Admin", company: "Prosciutto", level: "Senior", salary: 111, description: "Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI.", city: "New York", state: "NY", user_id: 2)
new_job_Sidney2 = Job.create(title: "Super Hero", company: "Prosciutto", level: "Intern", salary: 0, description: "Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI.", city: "New York", state: "NY", user_id: 2)
new_job_Sidney3 = Job.create(title: "World Saver", company: "Prosciutto", level: "Senior", salary: 500, description: "Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI.", city: "New York", state: "NY", user_id: 2)
new_job_Sidney4 = Job.create(title: "Community Organizer", company: "Prosciutto", level: "Senior", salary: 999, description: "Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI.", city: "New York", state: "NY", user_id: 2)

new_job_Sidney1 = Job.create(title: "Flight Specialist", company: "Wellensittich", level: "Senior", salary: 123, description: "Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI.", city: "New York", state: "NY", user_id: 3)
new_job_Sidney2 = Job.create(title: "Millet Grower", company: "Wellensittich", level: "Junior", salary: 23, description: "Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI.", city: "New York", state: "NY", user_id: 3)
new_job_Sidney3 = Job.create(title: "Front End Designer", company: "Wellensittich", level: "Intern", salary: 82, description: "Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI.", city: "New York", state: "NY", user_id: 3)
new_job_Sidney4 = Job.create(title: "Feeder", company: "Wellensittich", level: "Senior", salary: 182, description: "Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI.", city: "New York", state: "NY", user_id: 3)
